export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";

export const OPEN_REGISTER_MODAL = "OPEN_REGISTER_MODAL";
export const CLOSE_REGISTER_MODAL = "CLOSE_REGISTER_MODAL";

export const VIEW_GROUP = 'VIEW_GROUP';
export const VIEW_EVENT = 'VIEW_EVENT';

export const REFRESH_GROUPS = 'REFRESH_GROUPS';

export const OPEN_FORM_SUBMIT_MODAL = 'OPEN_FORM_SUBMIT_MODAL';
export const CLOSE_FORM_SUBMIT_MODAL = 'CLOSE_FORM_SUBMIT_MODAL';

export const UPDATE_USER_AVATAR = "UPDATE_USER_AVATAR";

export const UPDATE_GROUP = 'UPDATE_GROUP';

export const VIEW_PROFILE = 'VIEW_PROFILE';
export const VIEW_PROFILE_LOADING = 'VIEW_PROFILE_LOADING';
export const VIEW_PROFILE_ERROR = 'VIEW_PROFILE_ERROR';

export const CLEAR_TRIP = 'CLEAR_TRIP';

export const CREATE_CONTRACT = 'CREATE_CONTRACT';

export const VIEW_REQUEST = 'VIEW_REQUEST';