export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";

export const OPEN_REGISTER_MODAL = "OPEN_REGISTER_MODAL";
export const CLOSE_REGISTER_MODAL = "CLOSE_REGISTER_MODAL";

export const VIEW_GROUP = 'VIEW_GROUP';
export const VIEW_EVENT = 'VIEW_EVENT';

export const REFRESH_GROUPS = 'REFRESH_GROUPS';

export const OPEN_FORM_SUBMIT_MODAL = 'OPEN_FORM_SUBMIT_MODAL';
export const CLOSE_FORM_SUBMIT_MODAL = 'CLOSE_FORM_SUBMIT_MODAL';

export const UPDATE_USER_AVATAR = "UPDATE_USER_AVATAR";

export const UPDATE_GROUP = 'UPDATE_GROUP';

export const VIEW_PROFILE = 'VIEW_PROFILE';
export const VIEW_PROFILE_LOADING = 'VIEW_PROFILE_LOADING';
export const VIEW_PROFILE_ERROR = 'VIEW_PROFILE_ERROR';

export const CLEAR_TRIP = 'CLEAR_TRIP';

export const CREATE_CONTRACT = 'CREATE_CONTRACT';

export const VIEW_REQUEST = 'VIEW_REQUEST';
export const VIEW_CHAT = 'VIEW_CHAT';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';
export const VIEW_MESSAGE = 'VIEW_MESSAGE';

export const SELECTED_REQUEST = 'SELECTED_REQUEST';

export const UPDATE_CHAT_CONTENT = 'UPDATE_CHAT_CONTENT';
export const UPDATE_CHAT_HEADER = 'UPDATE_CHAT_HEADER';

export const FETCH_TOUR_SUCCESS = 'FETCH_TOUR_SUCCESS';
export const FETCH_TOUR_ERROR = 'FETCH_TOUR_ERROR';

export const SEARCH = 'SEARCH';

export const SAVE_SIGNATURE = 'SAVE_SIGNATURE';

export const DELETE_POST = 'DELETE_POST';

export const UPDATE_POST = 'UPDATE_POST';

export const SET_CHAT_CONNECTION = 'SET_CHAT_CONNECTION';