name: Build React App

on:
  push:
    branches:
      - develop 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: false  # This ensures the job fails if tests do not pass

      - name: Build the project
        run: npm run build
        if: success()  # This ensures the build runs only if the previous steps succeeded
